from .catalog_schemas import (
    BatchProductsResponse,
    PaginatedProductsResponse,
    PaginatedProvidersResponse,
    ProductCreate,
    ProductResponse,
    ProviderCreate,
    ProviderCreateResponse,
    ProviderResponse,
)
from .delivery_schemas import (
    RouteDetailResponse,
    RouteGenerationRequest,
    RouteGenerationResponse,
    RouteResponse,
    RoutesListResponse,
    RouteStatusUpdateRequest,
    ShipmentInRoute,
    ShipmentResponse,
    ShipmentStatusUpdateRequest,
    VehicleCreateRequest,
    VehicleInRoute,
    VehicleResponse,
    VehiclesListResponse,
    VehicleUpdateRequest,
)
from .enums import ProductCategory
from .inventory_schemas import (
    InventoryCreate,
    InventoryCreateRequest,
    InventoryCreateResponse,
    InventoryResponse,
    PaginatedInventoriesResponse,
    PaginatedWarehousesResponse,
    WarehouseCreate,
    WarehouseCreateResponse,
    WarehouseResponse,
)
from .seller_schemas import (
    PaginatedSalesPlansResponse,
    PaginatedSellersResponse,
    SalesPlanCreate,
    SalesPlanCreateResponse,
    SalesPlanResponse,
    SellerCreate,
    SellerCreateResponse,
    SellerResponse,
)

__all__ = [
    # Catalog schemas
    "ProviderCreate",
    "ProviderCreateResponse",
    "ProviderResponse",
    "ProductResponse",
    "ProductCreate",
    "PaginatedProvidersResponse",
    "PaginatedProductsResponse",
    "BatchProductsResponse",
    "ProductCategory",
    # Delivery schemas
    "RouteDetailResponse",
    "RouteGenerationRequest",
    "RouteGenerationResponse",
    "RouteResponse",
    "RoutesListResponse",
    "RouteStatusUpdateRequest",
    "ShipmentInRoute",
    "ShipmentResponse",
    "ShipmentStatusUpdateRequest",
    "VehicleCreateRequest",
    "VehicleInRoute",
    "VehicleResponse",
    "VehiclesListResponse",
    "VehicleUpdateRequest",
    # Inventory schemas
    "WarehouseCreate",
    "WarehouseCreateResponse",
    "WarehouseResponse",
    "PaginatedWarehousesResponse",
    "InventoryCreate",
    "InventoryCreateRequest",
    "InventoryCreateResponse",
    "InventoryResponse",
    "PaginatedInventoriesResponse",
    # Seller schemas
    "SellerCreate",
    "SellerCreateResponse",
    "SellerResponse",
    "PaginatedSellersResponse",
    "SalesPlanCreate",
    "SalesPlanCreateResponse",
    "SalesPlanResponse",
    "PaginatedSalesPlansResponse",
]
