version: '3.8'

services:
  client:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run python main.py runserver --port 8002 --reload
