networks:
  microservices:
    driver: bridge

services:
  client:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run python main.py runserver --port 8002 --reload
    depends_on:
      - client-db
    networks:
      - microservices

  client-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=client
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
