networks:
  microservices:
    driver: bridge

services:
  order:
    build: .
    ports:
      - "8005:8005"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8005 --reload"
    depends_on:
      - order-db
    networks:
      - microservices

  order-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
