services:
  order:
    build: .
    ports:
      - "8005:8005"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8005 --reload"
