version: '3.8'

networks:
  microservices:
    driver: bridge

services:
  order:
    build: .
    ports:
      - "8005:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - order-db
    networks:
      - microservices

  order-db:
    image: postgres:15
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
