version: '3.8'

networks:
  microservices:
    driver: bridge

services:
  bff:
    build: ./bff
    ports:
      - "8000:8000"
    volumes:
      - ./bff:/app
    env_file:
      - ./bff/.env
    command: poetry run python main.py runserver --port 8000 --reload
    depends_on:
      - catalog
      - client
      - delivery
      - inventory
      - order
      - seller
    networks:
      - microservices

  catalog:
    build: ./catalog
    ports:
      - "8001:8001"
    env_file:
      - ./catalog/.env
    volumes:
      - ./catalog:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8001 --reload"
    depends_on:
      - catalog-db
    networks:
      - microservices

  catalog-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices

  client:
    build: ./client
    ports:
      - "8002:8002"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
    command: poetry run python main.py runserver --port 8002 --reload
    depends_on:
      - client-db
    networks:
      - microservices

  client-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=client
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices

  delivery:
    build: ./delivery
    ports:
      - "8003:8003"
    env_file:
      - ./delivery/.env
    volumes:
      - ./delivery:/app
    command: poetry run python main.py runserver --port 8003 --reload
    depends_on:
      - delivery-db
    networks:
      - microservices

  delivery-db:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices

  inventory:
    build: ./inventory
    ports:
      - "8004:8004"
    env_file:
      - ./inventory/.env
    volumes:
      - ./inventory:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8004 --reload"
    depends_on:
      - inventory-db
    networks:
      - microservices

  inventory-db:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices

  order:
    build: ./order
    ports:
      - "8005:8005"
    env_file:
      - ./order/.env
    volumes:
      - ./order:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8005 --reload"
    depends_on:
      - order-db
    networks:
      - microservices

  order-db:
    image: postgres:15
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices

  seller:
    build: ./seller
    ports:
      - "8006:8006"
    env_file:
      - ./seller/.env
    volumes:
      - ./seller:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8006 --reload"
    depends_on:
      - seller-db
    networks:
      - microservices

  seller-db:
    image: postgres:15
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=seller
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
