networks:
  microservices:
    driver: bridge

services:
  bff:
    build: ./bff
    ports:
      - "8000:8000"
    env_file:
      - ./bff/.env
    networks:
      - microservices

  catalog:
    build:
      context: ./catalog
      target: app
    ports:
      - "8001:8000"
    env_file:
      - ./catalog/.env
    depends_on:
      - shared-db
      - localstack
    networks:
      - microservices

  client:
    build:
      context: ./client
      target: app
    ports:
      - "8002:8000"
    env_file:
      - ./client/.env
    depends_on:
      - shared-db
      - localstack
    networks:
      - microservices

  delivery:
    build:
      context: ./delivery
      target: app
    ports:
      - "8003:8000"
    env_file:
      - ./delivery/.env
    depends_on:
      - shared-db
      - localstack
    networks:
      - microservices

  inventory:
    build:
      context: ./inventory
      target: app
    ports:
      - "8004:8000"
    env_file:
      - ./inventory/.env
    depends_on:
      - shared-db
      - localstack
    networks:
      - microservices

  order:
    build:
      context: ./order
      target: app
    ports:
      - "8005:8000"
    env_file:
      - ./order/.env
    depends_on:
      - shared-db
      - localstack
    networks:
      - microservices

  seller:
    build:
      context: ./seller
      target: app
    ports:
      - "8006:8000"
    env_file:
      - ./seller/.env
    depends_on:
      - shared-db
      - localstack
    networks:
      - microservices

  shared-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=medisupply
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices

  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
      - "8007:8007"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - LOCALSTACK_WEB_UI=1
      - LOCALSTACK_WEB_UI_PORT=8007
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - microservices
