"""2025_10_18_add_denormalized_fields_to_inventory

Revision ID: 115738595904
Revises: d974948bc2ee
Create Date: 2025-10-18 00:15:09.867209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115738595904'
down_revision: Union[str, Sequence[str], None] = 'd974948bc2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('product_sku', sa.String(length=100), nullable=False))
    op.add_column('inventories', sa.Column('product_name', sa.String(length=500), nullable=False))
    op.add_column('inventories', sa.Column('warehouse_name', sa.String(length=255), nullable=False))
    op.add_column('inventories', sa.Column('warehouse_city', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'warehouse_city')
    op.drop_column('inventories', 'warehouse_name')
    op.drop_column('inventories', 'product_name')
    op.drop_column('inventories', 'product_sku')
    # ### end Alembic commands ###
