"""2025_10_17_Auto migration

Revision ID: d974948bc2ee
Revises: d8f5c9a1e234
Create Date: 2025-10-17 04:19:49.268773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd974948bc2ee'
down_revision: Union[str, Sequence[str], None] = 'd8f5c9a1e234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
