networks:
  microservices:
    driver: bridge

services:
  inventory:
    build: .
    ports:
      - "8004:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - inventory-db
    networks:
      - microservices

  inventory-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
