networks:
  microservices:
    driver: bridge

services:
  inventory:
    build: .
    ports:
      - "8004:8004"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8004 --reload"
    depends_on:
      - inventory-db
    networks:
      - microservices

  inventory-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
