"""2025_10_17_add_sku_to_products

Revision ID: 23dd0fb2dbe3
Revises: c3530bda1a0f
Create Date: 2025-10-17 19:00:56.485590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23dd0fb2dbe3'
down_revision: Union[str, Sequence[str], None] = 'c3530bda1a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'products', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
