"""2025_10_17_remove_status_description_from_products

Revision ID: f6e857c603d4
Revises: 23dd0fb2dbe3
Create Date: 2025-10-17 19:01:29.855689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e857c603d4'
down_revision: Union[str, Sequence[str], None] = '23dd0fb2dbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
