services:
  catalog:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8001 --reload"
