"""add_order_recived_event_table

Revision ID: 0d7d7a402644
Revises: 246cd2c23106
Create Date: 2025-11-09 19:33:16.453394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7d7a402644'
down_revision: Union[str, Sequence[str], None] = '246cd2c23106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_recived_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('microservice', sa.String(length=100), nullable=False),
    sa.Column('payload_snapshot', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_recived_event_event_id'), 'order_recived_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_order_recived_event_event_type'), 'order_recived_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_order_recived_event_microservice'), 'order_recived_event', ['microservice'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_recived_event_microservice'), table_name='order_recived_event')
    op.drop_index(op.f('ix_order_recived_event_event_type'), table_name='order_recived_event')
    op.drop_index(op.f('ix_order_recived_event_event_id'), table_name='order_recived_event')
    op.drop_table('order_recived_event')
    # ### end Alembic commands ###
