"""2025_11_01_Add visits table with indexes and constraints

Revision ID: 246cd2c23106
Revises: f1f4cf1a7f80
Create Date: 2025-11-01 10:29:28.522997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246cd2c23106'
down_revision: Union[str, Sequence[str], None] = 'f1f4cf1a7f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('fecha_visita', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notas_visita', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('archivos_evidencia', sa.String(), nullable=True),
    sa.Column('client_nombre_institucion', sa.String(), nullable=False),
    sa.Column('client_direccion', sa.String(), nullable=False),
    sa.Column('client_ciudad', sa.String(), nullable=False),
    sa.Column('client_pais', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('programada', 'completada', 'cancelada')", name='check_visit_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visits_client_id', 'visits', ['client_id'], unique=False)
    op.create_index('idx_visits_seller_date', 'visits', ['seller_id', 'fecha_visita'], unique=False)
    op.create_index('idx_visits_seller_date_status', 'visits', ['seller_id', 'fecha_visita', 'status'], unique=False)
    op.create_index('idx_visits_seller_id', 'visits', ['seller_id'], unique=False)
    op.create_index('idx_visits_status', 'visits', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visits_status', table_name='visits')
    op.drop_index('idx_visits_seller_id', table_name='visits')
    op.drop_index('idx_visits_seller_date_status', table_name='visits')
    op.drop_index('idx_visits_seller_date', table_name='visits')
    op.drop_index('idx_visits_client_id', table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
