"""2025_10_06_add sales plan model

Revision ID: 409cd1a9279c
Revises: b14647a1f98e
Create Date: 2025-10-06 22:16:48.871324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409cd1a9279c'
down_revision: Union[str, Sequence[str], None] = 'b14647a1f98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('sales_period', sa.String(length=50), nullable=False),
    sa.Column('goal_type', sa.Enum('SALES', 'ORDERS', name='goaltype'), nullable=False),
    sa.Column('goal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('accumulate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DEACTIVE', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_plans')
    # ### end Alembic commands ###
