"""2025_11_15_Auto migration

Revision ID: 9c6bd98233b4
Revises: 
Create Date: 2025-11-15 11:09:05.319300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6bd98233b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_recived_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('microservice', sa.String(length=100), nullable=False),
    sa.Column('payload_snapshot', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_recived_event_event_id'), 'order_recived_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_order_recived_event_event_type'), 'order_recived_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_order_recived_event_microservice'), 'order_recived_event', ['microservice'], unique=False)
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cognito_user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_user_id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('fecha_visita', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notas_visita', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('archivos_evidencia', sa.String(), nullable=True),
    sa.Column('client_nombre_institucion', sa.String(), nullable=False),
    sa.Column('client_direccion', sa.String(), nullable=False),
    sa.Column('client_ciudad', sa.String(), nullable=False),
    sa.Column('client_pais', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('programada', 'completada', 'cancelada')", name='check_visit_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visits_client_id', 'visits', ['client_id'], unique=False)
    op.create_index('idx_visits_seller_date', 'visits', ['seller_id', 'fecha_visita'], unique=False)
    op.create_index('idx_visits_seller_date_status', 'visits', ['seller_id', 'fecha_visita', 'status'], unique=False)
    op.create_index('idx_visits_seller_id', 'visits', ['seller_id'], unique=False)
    op.create_index('idx_visits_status', 'visits', ['status'], unique=False)
    op.create_table('sales_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('sales_period', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('accumulate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_plans')
    op.drop_index('idx_visits_status', table_name='visits')
    op.drop_index('idx_visits_seller_id', table_name='visits')
    op.drop_index('idx_visits_seller_date_status', table_name='visits')
    op.drop_index('idx_visits_seller_date', table_name='visits')
    op.drop_index('idx_visits_client_id', table_name='visits')
    op.drop_table('visits')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_order_recived_event_microservice'), table_name='order_recived_event')
    op.drop_index(op.f('ix_order_recived_event_event_type'), table_name='order_recived_event')
    op.drop_index(op.f('ix_order_recived_event_event_id'), table_name='order_recived_event')
    op.drop_table('order_recived_event')
    # ### end Alembic commands ###
