import logging
import time
from datetime import date
from typing import List
from uuid import UUID, uuid4

from sqlalchemy.ext.asyncio import AsyncSession

from src.application.ports import (
    RouteOptimizationPort,
    RouteRepositoryPort,
    ShipmentRepositoryPort,
    SQSEventPublisherPort,
    VehicleRepositoryPort,
)
from src.domain.entities import Route
from src.domain.exceptions import RouteOptimizationError

logger = logging.getLogger(__name__)


class GenerateRoutesUseCase:
    """Use case for generating optimized delivery routes."""

    def __init__(
        self,
        shipment_repository: ShipmentRepositoryPort,
        vehicle_repository: VehicleRepositoryPort,
        route_repository: RouteRepositoryPort,
        route_optimizer: RouteOptimizationPort,
        event_publisher: SQSEventPublisherPort,
        session: AsyncSession,
    ):
        self._shipment_repo = shipment_repository
        self._vehicle_repo = vehicle_repository
        self._route_repo = route_repository
        self._optimizer = route_optimizer
        self._event_publisher = event_publisher
        self._session = session

    async def execute(
        self,
        fecha_entrega_estimada: date,
        vehicle_ids: List[UUID],
    ) -> List[Route]:
        """
        Generate optimized routes for a given date.

        Args:
            fecha_entrega_estimada: Target delivery date
            vehicle_ids: List of vehicle IDs to use

        Returns:
            List of created routes
        """
        start_time = time.time()

        # Fetch pending shipments for date
        shipments = await self._shipment_repo.find_pending_by_date(fecha_entrega_estimada)
        if not shipments:
            logger.warning(f"No pending shipments for {fecha_entrega_estimada}")
            return []

        # Fetch vehicles
        vehicles = await self._vehicle_repo.find_by_ids(vehicle_ids)
        if not vehicles:
            raise RouteOptimizationError("No valid vehicles found")

        logger.info(
            f"Generating routes for {len(shipments)} shipments "
            f"with {len(vehicles)} vehicles"
        )

        # Optimize routes
        results = await self._optimizer.optimize_routes(shipments, vehicles)
        if not results:
            logger.warning("No routes generated by optimizer")
            return []

        # Create and save routes
        routes = []
        total_shipments = 0

        for result in results:
            route = Route(
                id=uuid4(),
                vehicle_id=result.vehicle.id,
                fecha_ruta=fecha_entrega_estimada,
                duracion_estimada_minutos=result.estimated_duration_minutes,
                total_distance_km=result.total_distance_km,
                total_orders=len(result.shipments),
            )

            # Add shipments to route
            for seq, shipment in enumerate(result.shipments, 1):
                route.add_shipment(shipment, seq)

            # Save route
            await self._route_repo.save(route)

            # Update shipments with route assignment
            await self._shipment_repo.update_many(result.shipments)

            routes.append(route)
            total_shipments += len(result.shipments)

        # Commit all routes and shipment updates
        await self._session.commit()
        logger.info(f"Committed {len(routes)} routes with {total_shipments} shipments to database")

        # Publish void event to trigger BFF refetch
        await self._publish_routes_generated()

        # Calculate generation time
        generation_time_ms = int((time.time() - start_time) * 1000)
        logger.info(f"Generated {len(routes)} routes with {total_shipments} shipments in {generation_time_ms}ms")

        return routes

    async def _publish_routes_generated(self) -> None:
        """Publish delivery_routes_generated void event to BFF queue."""
        try:
            await self._event_publisher.publish_routes_generated()
        except Exception as e:
            logger.error(f"Failed to publish routes generated event: {e}")
