networks:
  microservices:
    driver: bridge

services:
  seller:
    build: .
    ports:
      - "8006:8006"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "poetry run python main.py migrate && poetry run python main.py runserver --port 8006 --reload"
    depends_on:
      - seller-db
    networks:
      - microservices

  seller-db:
    image: postgres:15
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=seller
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
