networks:
  microservices:
    driver: bridge

services:
  seller:
    build: .
    ports:
      - "8006:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - seller-db
    networks:
      - microservices

  seller-db:
    image: postgres:15
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=seller
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
