version: '3.8'

services:
  seller:
    build: .
    ports:
      - "8006:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
