"""2025_11_15_Auto migration

Revision ID: a107dec12efa
Revises: 
Create Date: 2025-11-15 11:07:02.187643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a107dec12efa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('s3_bucket', sa.String(length=255), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_reports_created_at', 'order_reports', ['created_at'], unique=False)
    op.create_index('idx_order_reports_status', 'order_reports', ['status'], unique=False)
    op.create_index('idx_order_reports_user_id', 'order_reports', ['user_id'], unique=False)
    op.create_index('idx_order_reports_user_status', 'order_reports', ['user_id', 'status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_entrega_estimada', sa.Date(), nullable=True),
    sa.Column('direccion_entrega', sa.String(length=500), nullable=False),
    sa.Column('ciudad_entrega', sa.String(length=100), nullable=False),
    sa.Column('pais_entrega', sa.String(length=100), nullable=False),
    sa.Column('metodo_creacion', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('seller_email', sa.String(length=255), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('inventario_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('precio_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_city', sa.String(length=100), nullable=False),
    sa.Column('warehouse_country', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_index('idx_order_reports_user_status', table_name='order_reports')
    op.drop_index('idx_order_reports_user_id', table_name='order_reports')
    op.drop_index('idx_order_reports_status', table_name='order_reports')
    op.drop_index('idx_order_reports_created_at', table_name='order_reports')
    op.drop_table('order_reports')
    # ### end Alembic commands ###
