version: '3.8'

services:
  delivery:
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run python main.py runserver --port 8003 --reload
