version: '3.8'

networks:
  microservices:
    driver: bridge

services:
  delivery:
    build: .
    ports:
      - "8003:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - delivery-db
    networks:
      - microservices

  delivery-db:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - microservices
